on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_call:
    outputs:
      artifact-name:
        description: 'The name of the uploaded artifact'
        value: ${{ jobs.build.outputs.artifact-name }}

# Set permissions
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload-artifact.outputs.artifact-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: npm ci

      - name: Setup Emscripten
        run: npm run setup:emscripten

      - name: Build WebAssembly module
        run: npm run build:wasm:release

      - name: Build frontend
        run: npm run build

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: wfs-tools-web-build
          path: './dist'
