name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    # Add environment condition - only set environment for deployment, not PRs
    environment: ${{ github.event_name == 'pull_request' && '' || 'github-pages' }}
    steps:
      - name: Checkout
        uses: actions/checkout@latest
        with:
          submodules: 'recursive'

      - name: Setup Pages
        uses: actions/configure-pages@latest

      - name: Setup Node.js
        uses: actions/setup-node@latest
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: npm ci

      - name: Setup Emscripten
        run: npm run setup:emscripten

      - name: Build WebAssembly module
        run: npm run build:wasm:release

      - name: Build frontend
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@latest
        with:
          path: './dist'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # Only run deployment job when not a PR and pushing to main branch
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@latest
